import json,pathlib,csv
p=pathlib.Path(__file__).parent
a=json.loads((p/'analysis.json').read_text(encoding='utf-8'))
def item(id,title,tables,definition,caveats,rows=None,period=None,calculation=None):
 q={'id':id+'-evidence','source':{'label':'Requerimientos de establecimientos de Salud · Power BI Modeling MCP','tables':[{'name':s} for s in tables],'metricDefinitions':[{'label':title,'definition':definition}],'caveats':caveats}}
 if rows is not None:
  q.update({'rows':rows,'columns':list(rows[0]) if rows else [],'preview':{'kind':'aggregate','note':'Resultados agregados a partir del modelo abierto; vista de evidencia seleccionada.'}})
 if period:q['reportingPeriod']=period
 if calculation:q['methods']=[{'language':'calculation','code':calculation}]
 return {'id':id,'title':title,'queries':[q]}
items=[item('demanda','Evolución y concentración de la demanda',['GBA_Rendimientos','DIM_Geografia'],'Atenciones registradas: suma de consultas médicas, odontológicas, paramédicas e interconsultas. Municipios y regiones comparados con la geografía constante de la dimensión.', ['No son pacientes únicos ni demanda insatisfecha. La cobertura de registros cambia entre años. El gráfico regional guardado usa regiones históricas diferentes; la comparación homogénea aquí presentada se recalculó.'],[{'Año':r['year'],'Atenciones':r['demand']} for r in a['annual']],'2005–2024','121.826.050 − 50.466.975 = 71.359.075 atenciones adicionales (+141,4%).\nV y VI: (22.358.180 + 19.000.159) / 71.359.075 = 57,96% del crecimiento neto.\nLos cinco municipios de mayor aumento suman 23.663.540, equivalentes a 33,16% del aumento neto.'),
item('capacidad','Señales de saturación y subutilización',['GBA_Rendimientos','DIM_Establecimientos'],'Ocupación agregada = pacientes-día / días-cama disponibles. Clasificación del modelo: saturación entre 90% y 100%; subutilización hasta 40% con al menos 50 egresos por año informado.', ['Agudos es una clasificación inferida por camas, egresos y estadía hasta 30 días. Once de los 20 saturados tienen al menos un año con ocupación superior a 100%. Los nombres de algunos códigos cambian entre años.'],[{'Clasificación':k,'Establecimientos':v} for k,v in a['classes'].items()],'2022–2024'),
item('desempeno','Comparación relativa y evolución',['GBA_Rendimientos','DIM_Establecimientos'],'Estadía = días de estadía / egresos; mortalidad = defunciones / egresos. Referencias: medianas 2022–2024 de agudos de igual dependencia con al menos 100 egresos por año informado.', ['La marca de desempeño incluye 21 centros de estadía prolongada contra referencia aguda. Drozdowski se denomina rehabilitación y requiere validar el grupo de comparación. Estos indicadores no están ajustados por riesgo clínico. Las trayectorias citadas son absolutas; el informe no presenta medianas anuales.'],[{'Dependencia':k,'Mediana estadía (días)':v['los'],'Mediana mortalidad (%)':100*v['mort'],'Centros referencia':v['count']} for k,v in a['benchmarks'].items()],'2022–2024'),
item('revision','Correcciones y contenido prescindible',['Modelo semántico vivo','Definición PBIR guardada'],'Revisión de medidas, columnas calculadas, filtros y campos utilizados por las tres páginas frente a las preguntas solicitadas.', ['No se inspeccionaron el renderizado ni las interacciones de la ventana de Power BI. No se modificó el informe.'],None,None,'P3 mezcla valores históricos y ratios 2022–2024. Tabla, barras y línea filtran mortalidad relativa por 2, 2,5 y 4 respectivamente. La clasificación general permite estadía alta o mortalidad alta; 40 agudos con alerta sólo de estadía quedan excluidos por el filtro de mortalidad de la tabla. P1 usa región histórica; P2 no muestra pacientes-día ni egresos en sus tablas principales.')]
(p/'sources.json').write_text(json.dumps({'schemaVersion':1,'items':items},ensure_ascii=False),encoding='utf-8')
